### PR TITLE
Update to generator-jhipster v8

### LINKED ISSUE #1410: Migrate to JHipster v8
According to jhipster/generator-jhipster#23449, JHipster v8 is getting close. We should migrate and make sure everything works correctly.

### PR DESCRIPTION
**Pull request by hide212131**
Fixes #1410

### CODE REVIEW

**Comment by mraible** [comment]
@hide212131 There's a conflict in `package-lock.json`.

**Comment by mraible** [comment]
@hide212131 There are some conflicts that need to be fixed.

**Comment by hide212131** [comment]
The IOS-E2E in detox is now all green with ci.( Incorporating @zhyd1997 detox problem solving branch, Thanks! )
After this, refactoring and conflict resolution will finish my work.

**Comment by hide212131** [comment]
- Achievements:
  - Migration to JHipster8 blueprint
    - Same code generation as with JHipster7
  - Configuration similar to `generator-jhipster-ionic`
  - Passing of github ci tests: `Generator Tests`/`App Tests`/`IOS-E2E`
- Unresolved (Given up):
  - Heroku
  - Backward compatibility with JHipster7
  - Completion of github ci tests for `Sample App`

**Comment by hide212131** [comment]
Can someone please review and merge?

**Comment by DanielFran** [comment]
@hide212131 Can you fix the conflicts?

**Comment by mshima** [comment]
The root files I mean are the one generated by init generator:
- .editorconfig
- .gitattributes
- .gitignore
- .prettierrc.js.ejs

**Comment by hide212131** [comment]
@mshima Thank you for addressing the issue. I have adjusted the rest of the root files.

**Review by mshima — APPROVED** [review]

**Pull request merged**
