### PR TITLE
fix #889 Detox iOS error in GitHub Actions.

### LINKED ISSUE #889: Fix Detox tests running in GitHub Actions
**Describe the bug**

The Detox tests work just fine locally, but not on GitHub Actions with iOS. See https://github.com/wix/Detox/issues/3462#issuecomment-1234846538 for more information.

**Instructions To reproduce**

Run the iOS E2E action.

**Versions (please complete the following information):**

- JHipster React Native Version: `main`

### PR DESCRIPTION
**Pull request by mhmmdd**
1. Fix #889 Detox iOS error in GitHub Actions
"The "ios.sim.release" configuration utilizes a deprecated all-in-one schema, that is not supported by the current version of Detox."
2. Refactor new detox jest reporter.

### CODE REVIEW

**Comment by mraible** [comment]
@mhmmdd Can you please describe the problem this fixes and how to reproduce it. There's a lot of failing tests too.

**Comment by mhmmdd** [comment]
> @mhmmdd Can you please describe the problem this fixes and how to reproduce it. There's a lot of failing tests too.

@mraible I fixed the Detox iOS platform configuration error seems on Github iOS-E2E action. After solving this error other iOS specific component errors started appearing.

I have sent another PR (#1068) to resolve the failing tests. It has to be merged before this PR.

**Comment by mraible** [comment]
I re-enabled the [iOS-E2E](https://github.com/jhipster/generator-jhipster-react-native/actions/workflows/ios.yml) workflow that was previously disabled (because it didn't work).

**Comment by mraible** [comment]
@mhmmdd Sorry for the delay on this. It appears that the iOS e2e tests are still failing.

**Comment by mraible** [comment]
I'm doing to disable the iOS e2e tests again. Current failure is:

```
23:17:10.304 detox[15887] B lifecycle e2e/entities/department.spec.js
 FAIL  e2e/entities/department.spec.js
  ● Test suite failed to run

    TypeError: Listener is not a constructor

      16 |       WorkerAssignReporter,
      17 |     });
    > 18 |   }
         |    ^
      19 | }
      20 |
      21 | module.exports = CustomDetoxEnvironment;

      at CustomDetoxEnvironment.registerListeners (../node_modules/detox/runners/jest/testEnvironment/index.js:95:36)
      at new CustomDetoxEnvironment (environment.js:18:10)
```

**Review by mraible — CHANGES_REQUESTED** [review]
I don't know what needs to be done to fix things, but this PR does not solve the issue.

**Comment by DanielFran** [comment]
Superseded by https://github.com/jhipster/generator-jhipster-react-native/pull/1446

**Pull request closed without merging**
